#!/bin/bash

# global vars
USERNAME=guest
BREW=false

# programs that do not accept just "latest"
HELM_VERSION="v3.9.0"
HELMFILE_VERSION="0.145.2"
YQ_VERSION="v4.26.1"
DOCKER_COMPOSE_VERSION="v2.8.0"

function add_basic_software {
    sudo apt install -y git curl vim-gtk3 tcpdump jq dos2unix \
        apache2-utils sshpass tree gitk mlocate maven net-tools xz-utils

    sudo wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq && \
        sudo chmod +x /usr/bin/yq

    wget -qO- "https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz" | tar -xJv
    sudo cp "shellcheck-latest/shellcheck" /usr/bin/
    rm -rf shellcheck-latest
}

function add_brew_software {
    export NONINTERACTIVE=yes # otherwise brew asks for confirmation
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> "$HOME/.profile"
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    brew install gh
    brew install k9s
}

function enable_ssh_server {
    sudo apt install -y openssh-server
    sudo service ssh restart
}

function add_docker {
    # Docker dependencies
    sudo apt install -y apt-transport-https ca-certificates gnupg gnupg-agent lsb-release software-properties-common

    # Docker official key
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    # 3) Docker repository
    sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(. /etc/os-release; echo "$UBUNTU_CODENAME") stable"
    
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    # run docker as non-root
    sudo groupadd docker
    sudo usermod -aG docker $USERNAME

    # docker compose
    sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
         sudo chmod 755 /usr/local/bin/docker-compose
}

function add_kube_helm {
    local program

    program=helm-${HELM_VERSION}-linux-amd64.tar.gz
    wget https://get.helm.sh/${program}
    sudo tar -zxvf $program --strip-components=1 -C /usr/local/bin/ linux-amd64/helm
    rm $program

    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod u+x kubectl
    sudo mv kubectl /usr/local/bin/kubectl

    # install the helm diff plugin necessary for helmfile (default to latest)
    helm plugin install https://github.com/databus23/helm-diff
}

function add_helmfile {
    wget https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz
    tar -zxvf helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz
    rm helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz
    mv helmfile_linux_amd64 helmfile
    chmod u+x helmfile
    sudo mv helmfile /usr/local/bin
}

function add_extras {
    sudo apt install -y libxml-simple-perl libdate-simple-perl gnuplot
}

function add_cloud_software {
    add_docker
    add_kube_helm
    add_helmfile
}

function parse_args {
    while [[ $# -gt 0 ]]; do
        key="${1}"
        case ${key} in
            -h|--help)
	        help_and_exit
                ;;
            -u|--username)
                USERNAME="${2}"
                shift
                ;;
            --brew)
                BREW="true"
                shift
                ;;
            *)    # unknown option
                shift # past argument
                ;;
        esac
    done
}

function help_and_exit {
    echo "usage: $0 [options] -u <USERNAME>"
    echo "  -h, --help          print this help and exit"
    echo "  --brew              add brew and software"
    echo "  -u <USERNAME>       USERNAME is you username in the Linux host"
    echo "prerequisites: git"
    exit 1
}

function main {
    parse_args "$@"
    sudo apt update
    add_basic_software
    enable_ssh_server
    add_cloud_software
    [ "${BREW}" == "true" ] && add_brew_software
    add_extras
    echo "reboot to run docker as non-root"
}

main "$@"
exit 0
